### ISSUE TITLE
remove candidates option menu

### ISSUE THREAD

**Issue by tamzi** [muondu/Election-Platform#13]
The candidates are already fixed by the election day. It would be best to remove that option and simply give the user the option to vote.

MENU should be:

Good morning
are you a:
    a/voter
    b/staffmember

voter:
register
then vote:

vote:
These are the candidates you can vote for,
1. Person 1
2. Person 2
3. Person 3

**Comment by muondu** [comment]
K

**Comment by muondu** [comment]
I have done that change

**Comment by muondu** [comment]
I have fixed the issue
