### ISSUE TITLE
greating

### ISSUE THREAD

**Issue by mallimuondu** [muondu/Election-Platform#2]
you are telling me Good morning then Hi

in I have made some changes
https://github.com/muondu/Election-Platform/commit/4a4c4b81d5f4b14339d81da3d5795112e669eac7

**Comment by mallimuondu** [comment]
i am writing space bare  
Choose any of them:  

I did not understand you

then it exits

**Comment by mallimuondu** [comment]
when i am not AN ELIGIBLE voter it will repeat instead of exiting

**Comment by mallimuondu** [comment]
if you are a voter  then you put the first name as SPACE the last name as SPACE age  as SPACE it says ValueError: invalid literal for int() with base 10: ' instead of  pls put integer

**Comment by mallimuondu** [comment]
Enter your id_number: 12
The id number does not

?? what does that mean

it is supposed to be 

Enter your id_number(with 8 digits): 12
The id number does not have eight digits try again

**Comment by mallimuondu** [comment]
Enter your id_number: 12323232
[('AJAJ', 'AJA'), ('ajaj', 'aja')]
Which canidate do you want:  AJAJ
Thank you for voting. Good-Bye

Enter your first name: 

why is it starting again

**Comment by mallimuondu** [comment]
Enter your first name: mallimuondu
Enter your second name: muondu
[('AJAJ', 'AJA'), ('ajaj', 'aja'), ('mallimuondu', 'muondu')]
Enter your first name: 

why is it repeating

**Comment by mallimuondu** [comment]
[('AJAJ', 'AJA'), ('ajaj', 'aja'), ('mallimuondu', 'muondu')]
Which candidate are you searching for: mallimuondu
0

instead of  
[('AJAJ', 'AJA'), ('ajaj', 'aja'), ('mallimuondu', 'muondu')]
Which candidate are you searching for: mallimuondu
mallimuondu has 0 votes

**Comment by muondu** [comment]
> Enter your id_number: 12
> The id number does not
> 
> ?? what does that mean
> 
> it is supposed to be
> 
> Enter your id_number(with 8 digits): 12
> The id number does not have eight digits try again

My code it write
